### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Cydia2018** [billyceline/FCOS_pytorch#1]
想看一下您的数据集格式，感谢！

**Comment by billyceline** [comment]
才看到，不好意思，明天发给你，方便留个邮箱，两个txt文件

**Comment by billyceline** [comment]
这是我用的数据集格式
./VOC07&12/VOC2012/JPEGImages/2009_002988.jpg 282,182,368,250,14 70,113,198,228,14 220,111,302,233,14 186,109,314,210,14 303,123,380,239,14
每一段用空格分开，第一段为图片路径，之后的每一段是xmin,ymin,xmax,ymax,class_idx

**Comment by Cydia2018** [comment]
十分感谢！
